# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSopj7t_8syc7DMb6aL2dv0yoqWfmd5H
"""

pip install streamlit

!streamlit run ejemplo_titanic.py